"""
CLI command to display all available ANSI style and color codes in the terminal.
"""

from ..ansi import RenderSegment, S
from ..console import get_width

from pathlib import Path


def _st(style: str, /) -> RenderSegment:
    """Internal helper function to format styles for display in the `xulbux-lib ansi` command output."""

    return style if "." not in style else S.DIM(".").join(style.split("."))


def show_ansi() -> None:
    """CLI command function for `xulbux-lib ansi` command, which shows all possible styles using the `xulbux.ansi` API."""

    title = S.BOLD
    sep = (get_width(), S.DIM("─"))
    code = S.DIM | S.BR.BLACK

    S(
        S.RESET,
        title(" Text Styles ").center(*sep),
        "",
        (_st("BOLD               "), S.BOLD("Text")),
        code('                   S.BOLD("Text")'),
        (_st("DIM                "), S.DIM("Text")),
        code('                   S.DIM("Text")'),
        (_st("ITALIC             "), S.ITALIC("Text")),
        code('                   S.ITALIC("Text")'),
        (_st("UNDERLINE          "), S.UNDERLINE("Text")),
        code('                   S.UNDERLINE("Text")'),
        (_st("BLINK              "), S.BLINK("Text")),
        code('                   S.BLINK("Text")'),
        (_st("DOUBLE_UNDERLINE   "), S.DOUBLE_UNDERLINE("Text")),
        code('                   S.DOUBLE_UNDERLINE("Text")'),
        (_st("INVERSE            "), S.INVERSE("Text")),
        code('                   S.INVERSE("Text")'),
        (_st("HIDDEN             "), S.HIDDEN("Text")),
        code('                   S.HIDDEN("Text")'),
        (_st("STRIKETHROUGH      "), S.STRIKETHROUGH("Text")),
        code('                   S.STRIKETHROUGH("Text")'),
        "",
        title(" Foreground Colors ").center(*sep),
        "",
        (_st("BLACK              "), S.BLACK("Text")),
        code('                   S.BLACK("Text")'),
        (_st("BR.BLACK           "), S.BR.BLACK("Text")),
        code('                   S.BR.BLACK("Text")'),
        (_st("RED                "), S.RED("Text")),
        code('                   S.RED("Text")'),
        (_st("BR.RED             "), S.BR.RED("Text")),
        code('                   S.BR.RED("Text")'),
        (_st("GREEN              "), S.GREEN("Text")),
        code('                   S.GREEN("Text")'),
        (_st("BR.GREEN           "), S.BR.GREEN("Text")),
        code('                   S.BR.GREEN("Text")'),
        (_st("YELLOW             "), S.YELLOW("Text")),
        code('                   S.YELLOW("Text")'),
        (_st("BR.YELLOW          "), S.BR.YELLOW("Text")),
        code('                   S.BR.YELLOW("Text")'),
        (_st("BLUE               "), S.BLUE("Text")),
        code('                   S.BLUE("Text")'),
        (_st("BR.BLUE            "), S.BR.BLUE("Text")),
        code('                   S.BR.BLUE("Text")'),
        (_st("MAGENTA            "), S.MAGENTA("Text")),
        code('                   S.MAGENTA("Text")'),
        (_st("BR.MAGENTA         "), S.BR.MAGENTA("Text")),
        code('                   S.BR.MAGENTA("Text")'),
        (_st("CYAN               "), S.CYAN("Text")),
        code('                   S.CYAN("Text")'),
        (_st("BR.CYAN            "), S.BR.CYAN("Text")),
        code('                   S.BR.CYAN("Text")'),
        (_st("WHITE              "), S.WHITE("Text")),
        code('                   S.WHITE("Text")'),
        (_st("BR.WHITE           "), S.BR.WHITE("Text")),
        code('                   S.BR.WHITE("Text")'),
        "",
        title(" Background Colors ").center(*sep),
        "",
        (_st("BG.BLACK           "), (S.BG.BLACK.as_text_fg() | S.BG.BLACK)(" Text ")),
        code('                   S.BG.BLACK(" Text ")'),
        (_st("BG.BR.BLACK        "), (S.BG.BR.BLACK.as_text_fg() | S.BG.BR.BLACK)(" Text ")),
        code('                   S.BG.BR.BLACK(" Text ")'),
        (_st("BG.RED             "), (S.BG.RED.as_text_fg() | S.BG.RED)(" Text ")),
        code('                   S.BG.RED(" Text ")'),
        (_st("BG.BR.RED          "), (S.BG.BR.RED.as_text_fg() | S.BG.BR.RED)(" Text ")),
        code('                   S.BG.BR.RED(" Text ")'),
        (_st("BG.GREEN           "), (S.BG.GREEN.as_text_fg() | S.BG.GREEN)(" Text ")),
        code('                   S.BG.GREEN(" Text ")'),
        (_st("BG.BR.GREEN        "), (S.BG.BR.GREEN.as_text_fg() | S.BG.BR.GREEN)(" Text ")),
        code('                   S.BG.BR.GREEN(" Text ")'),
        (_st("BG.YELLOW          "), (S.BG.YELLOW.as_text_fg() | S.BG.YELLOW)(" Text ")),
        code('                   S.BG.YELLOW(" Text ")'),
        (_st("BG.BR.YELLOW       "), (S.BG.BR.YELLOW.as_text_fg() | S.BG.BR.YELLOW)(" Text ")),
        code('                   S.BG.BR.YELLOW(" Text ")'),
        (_st("BG.BLUE            "), (S.BG.BLUE.as_text_fg() | S.BG.BLUE)(" Text ")),
        code('                   S.BG.BLUE(" Text ")'),
        (_st("BG.BR.BLUE         "), (S.BG.BR.BLUE.as_text_fg() | S.BG.BR.BLUE)(" Text ")),
        code('                   S.BG.BR.BLUE(" Text ")'),
        (_st("BG.MAGENTA         "), (S.BG.MAGENTA.as_text_fg() | S.BG.MAGENTA)(" Text ")),
        code('                   S.BG.MAGENTA(" Text ")'),
        (_st("BG.BR.MAGENTA      "), (S.BG.BR.MAGENTA.as_text_fg() | S.BG.BR.MAGENTA)(" Text ")),
        code('                   S.BG.BR.MAGENTA(" Text ")'),
        (_st("BG.CYAN            "), (S.BG.CYAN.as_text_fg() | S.BG.CYAN)(" Text ")),
        code('                   S.BG.CYAN(" Text ")'),
        (_st("BG.BR.CYAN         "), (S.BG.BR.CYAN.as_text_fg() | S.BG.BR.CYAN)(" Text ")),
        code('                   S.BG.BR.CYAN(" Text ")'),
        (_st("BG.WHITE           "), (S.BG.WHITE.as_text_fg() | S.BG.WHITE)(" Text ")),
        code('                   S.BG.WHITE(" Text ")'),
        (_st("BG.BR.WHITE        "), (S.BG.BR.WHITE.as_text_fg() | S.BG.BR.WHITE)(" Text ")),
        code('                   S.BG.BR.WHITE(" Text ")'),
        "",
        title(" Custom Colors & Links ").center(*sep),
        "",
        (_st("hex()              "), S.hex("#FF6070")("#FF6070")),
        code('                   S.hex("#FF6070")("#FF6070")'),
        (_st("rgb()              "), S.rgb(255, 96, 112)("rgb(255, 96, 112)")),
        code('                   S.rgb(255, 96, 112)("rgb(255, 96, 112)")'),
        (_st("color256()         "), S.color256(210)("color256(210)")),
        code('                   S.color256(210)("color256(210)")'),
        (_st("BG.hex()           "), (S.BG.hex("#0064FF").as_text_fg() | S.BG.hex("#0064FF"))(" #0064FF ")),
        code('                   S.BG.hex("#0064FF")(" #0064FF ")'),
        (_st("BG.rgb()           "), (S.BG.rgb(0, 100, 255).as_text_fg() | S.BG.rgb(0, 100, 255))(" rgb(0, 100, 255) ")),
        code('                   S.BG.rgb(0, 100, 255)(" rgb(0, 100, 255) ")'),
        (_st("BG.color256()      "), (S.BG.color256(69).as_text_fg() | S.BG.color256(69))(" color256(69) ")),
        code('                   S.BG.color256(69)(" color256(69) ")'),
        (_st("link()             "), (S.hex("89F") | S.link("https://xul.is"))("xul.is")),
        code('                   S.link("https://xul.is")("xul.is")'),
        (
            _st("link() "),
            S.DIM("[folder]"),
            "    ",
            (S.hex("89F") | S.link(Path.cwd()))("Click here to open the CWD in your file explorer!"),
        ),
        code('                   S.link(Path.cwd())("Click here to open the CWD in your file explorer!")'),
        "",
        sep="\n",
    ).print()
